import { Component, ChangeDetectionStrategy, signal } from '@angular/core';

interface FaqItem {
  question: string;
  answer: string;
}

@Component({
  selector: 'app-faq',
  templateUrl: './faq.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FaqComponent {
  activeIndex = signal<number | null>(null);

  faqs: FaqItem[] = [
    {
      question: 'What kind of projects do you finish?',
      answer: 'We specialize in modern web applications built with tools like React, Angular, Vue, Node.js, and Python. We can take on most projects generated by AI code assistants or built on no-code platforms, as long as we can access the underlying code.'
    },
    {
      question: 'How does the "We Finish It" process work?',
      answer: 'It starts with you submitting your project repository and goals. Our senior engineers perform a detailed code audit to identify gaps in functionality, security, and scalability. We then provide a fixed-price quote and a clear timeline. Once approved, we get to work fixing bugs, writing code, and deploying the finished product.'
    },
    {
      question: 'What if I don\'t have any code yet?',
      answer: 'FINISH is a last-mile service, so our focus is on completing existing projects that are at least 70-80% complete. We don\'t typically build applications from scratch.'
    },
    {
      question: 'Who owns the intellectual property?',
      answer: 'You do. 100%. All code we write and deliver for your project is your intellectual property. We retain no rights to the completed work.'
    },
    {
      question: 'Is the finished code secure and reliable?',
      answer: 'Absolutely. Our reputation depends on it. All work is performed by senior engineers who follow industry best practices for security and reliability. We conduct rigorous testing and a quality assurance pass before handing any project over.'
    }
  ];

  toggleFaq(index: number) {
    this.activeIndex.update(currentIndex => (currentIndex === index ? null : index));
  }
}